#!/sbin/openrc-run
# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

supervisor="supervise-daemon"

name="nginx-prometheus-exporter daemon"
description="Nginx Prometheus Exporter"
command=/usr/bin/nginx-prometheus-exporter
command_args="${exporter_args}"

depend() {
    need net
    use logger
}

reload() {
    ebegin "Reloading nginx-prometheus-exporter configuration"
    ${supervisor} ${RC_SVCNAME} --signal HUP
    eend $?
}
